name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 깃허브 최신 코드 가져오기
      uses: actions/checkout@v4

    - name: 도커 허브 로그인 인증하기
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 백엔드 이미지 빌드 및 도커허브로 Push
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/memo-backend:latest

    - name: 프론트엔드 이미지 빌드 및 도커허브로 Push
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/memo-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: AWS EC2 원격 SSH 접속 후 배포 명령어 실행
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app/infra-practice
          git pull origin main
          docker compose pull
          docker compose up -d --build
          docker image prune -f
